# Site settings
title: Cinthia Katiane
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://cinthiakatiane.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Cinthia Katiane'
  email: josh@joshgerdes.com
  twitter_username: cinthiakatiane
  facebook_username: cinthia.katiane
  github_username:  cinthiakatiane
  linkedin_username:  cinthiakatiane

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
